### ISSUE TITLE
Affichage des resultats

### ISSUE THREAD

**Issue by barodeur** [voteetvous/app#10]
- [ ] Afficher la photo du candidat à droite

<img width="379" alt="cursor_and_voteetvous_sketch" src="https://cloud.githubusercontent.com/assets/303170/23586206/c0d88368-0190-11e7-8138-e44df17fa5bd.png">

**Comment by bkurc** [comment]
Tu pourrais laisser juste les numéro (sans er, nd, eme etc.) ? De plus, changer la photo de Fillon et Hamon, même provisoirement, afin que je puisse faire un screenshot et l'envoyer aux contacts média ? ;)

**Comment by Albanksy** [comment]
![voteetvous-app-dev_s3-website_eu-central-1_amazonaws_com](https://cloud.githubusercontent.com/assets/11016867/23680893/281efd6a-038d-11e7-96d6-bfa94b19bcfd.png)
Rééquilibrer les noms à la hauteur des chiffres

**Comment by Albanksy** [comment]
### Taille des 3 résultats
Taille identique des 3 résultats

**Comment by Albanksy** [comment]
### Test nom
Peux-tu faire un test avec le nom Nicolas Dupont-Aignan écrit sur :
* une ligne entière
* le prénom initial et nom entier
* le nom sur deux lignes

**Comment by Albanksy** [comment]
### Barre de comptabilité
Une seule couleur, trouver une belle, on pensait au bleu de "Résultats complets"

**Comment by barodeur** [comment]
Le design à été implementé
