### ISSUE TITLE
Logo carte question

### ISSUE THREAD

**Issue by Albanksy** [voteetvous/app#15]
Chaque question a un symbole lui correspondant. Peut-on avoir uniquement des symboles ronds pour l'homogénéité graphique ?

**Comment by barodeur** [comment]
Oui, mais il faut les trouver. 
Pour rappel, la principale resource pour les trouver est https://thenounproject.com/
Il es possible de télécharger en format SVG et d'intégrer les icones dans un cercle.
Il est très important de citer les auteurs des icones dans l'application ( dédier un lien et puis une page à partir des résultats ).
