### ISSUE TITLE
Font

### ISSUE THREAD

**Issue by Albanksy** [voteetvous/app#20]
Dans Sketch, c'est apparemment Helvetica Neue. Sur PC, la police est Times New Roman (cf. screenshot). Quelle police allons-nous utiliser ?

Notre logo utilise Open Sans (Google Fonts) mais c'est comme tu veux. Helvetica Neue est très belle parce que légère

![img_12032017_200401_0](https://cloud.githubusercontent.com/assets/11016867/23836503/dd707fbe-0779-11e7-954a-14441fa6afee.png)

**Comment by barodeur** [comment]
Bonne remarque, j'aimerais utilise une font système le plus possible pour avoir une application légère et rapide au chargement.
Je dois donc chercher une alternative pour windows.
