### ISSUE TITLE
Bouton pour partager l'app

### ISSUE THREAD

**Issue by Albanksy** [voteetvous/app#22]
Ajouter un bouton pour partager l'app sur chaque carte --> as-tu une idée ?

Ajouter un gros bouton clair pour partager l'app sur la Carte résultats et aussi sur la page résultats

**Comment by barodeur** [comment]
Le bouton pour partage l'app doit être en dehors de la carte. Car sinon les utilisateurs penseront que c'est pour partager la carte.
