### ISSUE TITLE
Pages Résultats

### ISSUE THREAD

**Issue by Albanksy** [voteetvous/app#23]
Onglet | "Par candidats" | "Par question"
------------ | ------------ | ------------
Design | Reprise du design de la Carte résultats : liste de 1 à X avec nom du candidat, barre de compatibilité et tête à droite  | Même design, mais cette fois avec les symboles des questions à droite et sans barre de compatibilité
Scroll général | Scroll haut-bas | Scroll haut-bas
Comment voir les détails ? | Tap sur le nom d'un candidat : ouverture d'un espace, à l'intérieur de cet espace, on peut faire défiler des petites cartes avec le symbole et la question | Tap sur le nom d'une question : ouverture d'un espace, à l'intérieur de cet espace, on peut faire défiler les têtes des candidats avec un cercle coloré autour qui donne leur réponse (vert, rouge ou gris)
Justifications | Par tap sur la question | Par tap sur le candidat
Comment reconnaître une similitude / différence entre le candidat et l'utilisateur ? | ? | ?

**Comment by bkurc** [comment]
Quid de la barre de progression des résultats ? On affiche en plus un pourcentage ou un nombre de réponses communes/différences ?

**Comment by Albanksy** [comment]
Pas de pourcentage. Par contre, on peut le nombre de réponses communes/différences : @barodeur t'as des exemples ?
