### ISSUE TITLE
Remplacer les icônes par un pouce vers le haut et vers le bas ou du texte "D'accord" ...

### ISSUE THREAD

**Issue by barodeur** [voteetvous/app#3]
**Actuellement**
<img width="189" alt="voteetvous-app-dev_s3-website_eu-central-1_amazonaws_com" src="https://cloud.githubusercontent.com/assets/303170/23502444/33623e34-ff38-11e6-9e16-c60598fce481.png">

**Possible remplacement**
<img width="138" alt="voteetvous_sketch" src="https://cloud.githubusercontent.com/assets/303170/23502459/3db77200-ff38-11e6-8c4a-16affb497398.png">

**Comment by barodeur** [comment]
Alban propose :
> Penses-tu pouvoir faire un essai avec "D'accord" / "Pas d'accord" écrits en toutes lettres ?

Je pense que c'est une bonne idée, il faut tester, je vais essayer directement sur le design de faire quelque chose ( avec Sketch ).

**Comment by barodeur** [comment]
<img width="236" alt="voteetvous_sketch" src="https://cloud.githubusercontent.com/assets/303170/23503959/f89ff0e2-ff3d-11e6-8072-701a0b64d084.png">

<img width="310" alt="voteetvous_sketch" src="https://cloud.githubusercontent.com/assets/303170/23504137/8bbf666e-ff3e-11e6-95e4-b14792be64a3.png">

**Comment by barodeur** [comment]
Pour l'instant je vais rester avec la solution du V et de X.

C'est peut-être sur ce genre de points qu'un designer pourra intervenir plus tard.

**Comment by bkurc** [comment]
Cooooool

**Comment by barodeur** [comment]
@bkurc qu'est ce qui est cool ? :P 
Le dernier commentaire ou un des designs précédents ?

**Comment by Albanksy** [comment]
@barodeur Reste avec les X et V pour l'instant effectivement. C'est plus simple. On verra ce week-end avec les autres.

**Comment by barodeur** [comment]
Je ferme pour #19 #4
