### ISSUE TITLE
Ajouter la réponse "indifférent"

### ISSUE THREAD

**Issue by barodeur** [voteetvous/app#4]
Le bouton sera placé sous les deux boutons OK et NOK.

<img width="177" alt="voteetvous_sketch" src="https://cloud.githubusercontent.com/assets/303170/23502370/ea742ed0-ff37-11e6-8e88-341725ad4b06.png">

L'animation de la carte sera juste un fadeout, et peut-être également un léger zoom

**Comment by Albanksy** [comment]
### Ajouter un bouton Indifférent
Le mot "Indifférent" est à ajouter sous forme d'un **bouton**. Carré ou rectangle (plutôt rectangle ?), à voir ce que ça rend au final. Couleur grise, tout de même lisible (davantage qu'actuellement)

**Comment by barodeur** [comment]
Quand vous dite que actuellement c'est par rapport à ce qui en en ligne ou par rapport au screenshot plus haut ?
