### ISSUE TITLE
URGENT | Ordre des questions

### ISSUE THREAD

**Issue by barodeur** [voteetvous/app#47]
Ordre envoyé par Antoni

```
26 - 31 - 18 - 8 -51 - 40 - 27 - 13 - 6 - 22 - 44 - 52 - 28 - 17 -9 - 56 - 42 _ 55 - 21 - 43 - 47 - 33 - 54 - 12 - 48 
```

**Comment by bkurc** [comment]
@barodeur je te donne l'ordre définitif des questions : https://docs.google.com/spreadsheets/d/1lASO-TQL3hOz3_QqFfMg6bxmPfLPNV3tnfT_OXchMbg/edit#gid=0 

C'est la colonne C du tableau. Serait-il possible de changer l'ordre aujourd'hui ?

**Comment by barodeur** [comment]
@bkurc @Albanksy @afourn  On peut maintenant changer l'ordre dans l'admin.
