### ISSUE TITLE
Écran de présentation

### ISSUE THREAD

**Issue by barodeur** [voteetvous/app#5]
Il faut probablement ajouter un écran initial de présentation de l'outil avant de balancer la première question.

**Comment by bkurc** [comment]
Pourrais-tu proposer un modèle ?

**Comment by Albanksy** [comment]
Proposition : afficher toutes les têtes des candidats dans des cercles. Ces mêmes têtes seront réutilisées sur la carte "résultats".

**Comment by Albanksy** [comment]
### Titre
Vote&Vous

### Phrase d'accroche
"De quel candidat êtes-vous le plus proche ?" --> cette phrase changera probablement. Prendre ça comme exemple.

### Mosaïque candidats
Tête des candidats dans des cercles. Faire attention aux couleurs.
