### ISSUE TITLE
Changer les metadata de app.vote-et-vous.fr

### ISSUE THREAD

**Issue by Albanksy** [voteetvous/app#63]

**Comment by Albanksy** [comment]
Voici les bonnes metadata:
`<meta property="og:image" content="https://www.vote-et-vous.fr/uploads/2/6/5/0/26507687/vote0003-facebook-1200x628px_orig.jpg"/>`
`<meta name="twitter:card" content="summary" />`
`<meta name="twitter:site" content="@voteetvous" />`
`<meta name="twitter:creator" content="@voteetvous" />`
`<meta property="og:description" content="Testez vos affinités politiques et comparez vos opinions à celles des candidats à l’élection présidentielle 2017 avec notre boîte à vote !" />`

**Comment by barodeur** [comment]
C'est bon.
